name:          Decisionary Engineering Best Practices
title:         Decisionary Engineering Best Practices
description:   Project engineering best practices used by Decisionary (h/t 10up, XWP).
url:           https://decisionary.github.io/engineering-best-practices/
author:
  name:    Decisionary
  email:   engage@decisionarytech.com
  github:  decisionary
  twitter: decisionary

markdown:      redcarpet
permalink:     pretty
highlighter:   pygments
encoding:      utf-8
redcarpet:
  extensions: [with_toc_data]
sass:
  sass_dir: _includes/_sass
CONFIG:
  BASE_PATH: https://decisionary.github.io/engineering-best-practices

  ASSET_PATH: false
